# Generated by Django 5.1.3 on 2024-11-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('profession', models.CharField(max_length=255)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('mobile_number', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/users')),
                ('membership_type', models.CharField(choices=[('Regular', 'Regular'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Regular', max_length=10)),
                ('body_type', models.CharField(choices=[('Slim', 'Slim'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('workout_plan_type', models.CharField(choices=[('Cardio', 'Cardio'), ('Day_1', 'Day 1'), ('Day_2', 'Day 2'), ('Day_3', 'Day 3'), ('Day_1_plus_Cardio', 'Day 1 + Cardio'), ('Day_2_plus_Cardio', 'Day 2 + Cardio'), ('Day_3_plus_Cardio', 'Day 3 + Cardio')], default='Cardio', max_length=20)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
