# Generated by Django 5.1.3 on 2024-11-20 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerGym_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersActivity',
            fields=[
                ('memActivites_id', models.AutoField(primary_key=True, serialize=False)),
                ('locker_no', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('gym_entry', models.DateTimeField(blank=True, null=True)),
                ('gym_exit', models.DateTimeField(blank=True, null=True)),
                ('activity_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=15)),
                ('due_amount', models.IntegerField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], default='due', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_members_activities', to='powerGym_app.member')),
            ],
        ),
    ]
