# Generated by Django 5.1.3 on 2024-11-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerGym_app', '0002_membersactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('Admin', 'Admin'), ('Trainer', 'Trainer'), ('Employee', 'Employee')], default='Member', max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
