# Generated by Django 5.1.3 on 2024-11-27 18:12

import django.db.models.deletion
import powerGym_app.model.memberPaymentsModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerGym_app', '0003_member_role_alter_member_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPaymentsModel',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('paid_amount', models.IntegerField()),
                ('paid_month', models.CharField(choices=powerGym_app.model.memberPaymentsModel.generate_month_year_choices, default=powerGym_app.model.memberPaymentsModel.default_month_year, max_length=20)),
                ('payment_desc', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Others', 'Others')], default='Cash', max_length=15)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], max_length=15)),
                ('due_amount', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_member', models.ForeignKey(limit_choices_to={'role': 'Member'}, on_delete=django.db.models.deletion.CASCADE, related_name='gym_members_payments', to='powerGym_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerActivityModel',
            fields=[
                ('traner_act_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer_entry', models.DateTimeField(blank=True, null=True)),
                ('trainer_exit', models.DateTimeField(blank=True, null=True)),
                ('duty_shift', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20)),
                ('morning_shift_status', models.BooleanField(default=False)),
                ('evening_shift_status', models.BooleanField(default=False)),
                ('worked_duty', models.CharField(blank=True, max_length=15)),
                ('holiday', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'Trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='gym_trainers_activities', to='powerGym_app.member')),
            ],
        ),
    ]
